import * as core from "@actions/core";

/**
 * Resolve the action's inputs into a single config object, applying logical
 * fallbacks. There is no config file — every setting is an optional input.
 */

/**
 * Parse a list-style input: comma- or newline-separated, trimmed, no blanks.
 *
 * @param {string} raw
 * @returns {string[]}
 */
export function parseList(raw) {
	return raw
		.split(/[\n,]/)
		.map((item) => item.trim())
		.filter(Boolean);
}

/**
 * Parse the JSON `variables` input into a plain object. Empty input → {}.
 *
 * @param {string} raw
 * @returns {Record<string, unknown>}
 */
export function parseVariables(raw) {
	const trimmed = raw.trim();
	if (!trimmed) return {};
	let parsed;
	try {
		parsed = JSON.parse(trimmed);
	} catch (err) {
		const message = err instanceof Error ? err.message : String(err);
		throw new Error(`The "variables" input must be valid JSON: ${message}`, { cause: err });
	}
	if (parsed == null || typeof parsed !== "object" || Array.isArray(parsed)) {
		throw new Error('The "variables" input must be a JSON object.');
	}
	return parsed;
}

/**
 * Read a boolean input, returning a fallback when the input is unset.
 *
 * @param {string} name
 * @param {boolean} fallback
 * @returns {boolean}
 */
function booleanInput(name, fallback) {
	const raw = core.getInput(name);
	if (!raw) return fallback;
	return core.getBooleanInput(name);
}

/**
 * @typedef {Object} WeaverConfig
 * @property {string} templatesDir Directory of template `*.md` files.
 * @property {string} targetFile File to inject into within each repo.
 * @property {"*" | string[]} repos Explicit repo list or "*" for all.
 * @property {string[]} exclude Repo names to skip.
 * @property {boolean} skipForks
 * @property {boolean} skipArchived
 * @property {Record<string, unknown>} variables User-supplied variables.
 * @property {string} managedNotice
 * @property {string} commitMessage
 * @property {string} branch Head branch name for the PR.
 * @property {string} base Base branch ("" → each repo's default branch).
 * @property {string} prTitle
 * @property {string} prBody
 * @property {boolean} dryRun
 * @property {number} maxValueLength
 */

/**
 * Build the resolved config from action inputs and the workflow context.
 *
 * @param {{ repo: { owner: string } }} context
 * @returns {WeaverConfig}
 */
export function loadConfig(context) {
	const reposRaw = core.getInput("repos").trim();
	const maxRaw = core.getInput("max-value-length").trim();

	return {
		org: context.repo.owner,
		templatesDir: core.getInput("templates").trim() || "templates",
		targetFile: core.getInput("target-file").trim() || "README.md",
		repos: !reposRaw || reposRaw === "*" ? "*" : parseList(reposRaw),
		exclude: parseList(core.getInput("exclude")),
		skipForks: booleanInput("skip-forks", true),
		skipArchived: booleanInput("skip-archived", true),
		variables: parseVariables(core.getInput("variables")),
		managedNotice:
			core.getInput("managed-notice").trim() ||
			"auto-generated by Weaver — do not edit between these markers",
		commitMessage:
			core.getInput("commit-message").trim() || "chore: sync templates via Weaver [skip ci]",
		branch: core.getInput("branch").trim() || "weaver/sync-templates",
		base: core.getInput("base").trim(),
		prTitle: core.getInput("pr-title").trim() || "chore: sync templates via Weaver",
		prBody:
			core.getInput("pr-body").trim() ||
			"Automated template sync by [Weaver](https://github.com/allonsy-studio/actions-weaver). Updated blocks: {{ blocks }}.",
		dryRun: booleanInput("dry-run", false),
		maxValueLength: maxRaw ? Number(maxRaw) : 1000,
	};
}
